shopt -s histappend
export HISTSIZE=5000
export HISTCONTROL="erasedups"
export PROMPT_COMMAND="history -a"
export HISTIGNORE="l:ls -la:l[lhs]:h:..:...:cd:[bf]g:exit"
export PAGER=less
export LESS="-i -r -X"

test -r /usr/bin/virtualenvwrapper.sh && . /usr/bin/virtualenvwrapper.sh
export WORKON_HOME=/opt/virtualenvs
# To tell pip to only run if there is a virtualenv currently activated, and to bail if not, use:
export PIP_REQUIRE_VIRTUALENV=true
export PIP_VIRTUALENV_BASE=$WORKON_HOME

function psa () {
	if [ $1 ]; then
		ps auxwwww | grep -v grep | grep -i $1
	else
		ps auxwwww
	fi
}

function h () {
	if [ $1 ]; then
		history | grep -i $1 | tail -250 | grep -i $1
	else
		history | tail -250
	fi
}
